In the examples, listen on 0.0.0.0 instead of 127.0.0.1 #664
poem-web/poem pull request #672
Opened 2023-10-12 11:15 UTC by schitcrafter

#664

2023-10-16 12:56 UTC, viell-dev requested changes
Looks like you did a search-and-replace. You also replaced some outgoing IP addresses.

2023-10-16 12:56 UTC, viell-dev commented on examples/poem/mongodb/src/main.rs
> +    let mongodb = Client::with_uri_str("mongodb://0.0.0.0:27017")
Connecting to 0.0.0.0 isn't strictly speaking valid. (But, in practice, it should be equivalent to connecting to localhost.)

2023-10-16 12:56 UTC, viell-dev commented on examples/poem/redis-session/src/main.rs
> +    let client = Client::open("redis://0.0.0.0/").unwrap();
Connecting to 0.0.0.0 isn't strictly speaking valid. (But, in practice, it should be equivalent to connecting to localhost.)

2023-10-16 12:56 UTC, viell-dev commented on examples/poem/websocket-chat/src/main.rs
> +            ws = new WebSocket("ws://0.0.0.0:3000/ws/" + nameInput.value);
Connecting to 0.0.0.0 isn't strictly speaking valid. (But, in practice, it should be equivalent to connecting to localhost.)

2023-11-18 01:59 UTC, merged

2023-11-18 01:59 UTC, sunli829 commented
thanks 😂